runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest